---
- hosts: "*"
  become: true
  tasks:
    - name: Update all packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        upgrade: "yes"
    - name: Update all distro packages
      apt:
        upgrade: "dist"
    - name: Check if reboot is needed
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
